const progress=document.querySelector('.progress');const header=document.querySelector('.site-header');const menuToggle=document.querySelector('.menu-toggle');const nav=document.querySelector('.nav');
const setProgress=()=>{const max=document.documentElement.scrollHeight-innerHeight; if(progress)progress.style.width=`${max>0?(scrollY/max)*100:0}%`};
addEventListener('scroll',()=>{setProgress();header?.classList.toggle('scrolled',scrollY>20)},{passive:true});setProgress();
if(menuToggle&&nav){menuToggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');menuToggle.classList.toggle('open',open);menuToggle.setAttribute('aria-expanded',String(open));menuToggle.setAttribute('aria-label',open?'Close navigation':'Open navigation')});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menuToggle.classList.remove('open');menuToggle.setAttribute('aria-expanded','false')}))}
const revealItems=document.querySelectorAll('.reveal,.split-section,.experience-section,.projects-section,.skills-section,.education-section,.contact-section,.resume-section,.frame-card,.catalog-row,.skill-group,.education-card,.education-item');revealItems.forEach(el=>el.classList.add('reveal'));const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');revealObserver.unobserve(entry.target)}}),{threshold:.08,rootMargin:'0px 0px -40px'});revealItems.forEach((el,i)=>{el.style.transitionDelay=`${Math.min(i%6,5)*45}ms`;revealObserver.observe(el)});
const sections=[...document.querySelectorAll('main section[id]')];const navLinks=[...document.querySelectorAll('.nav a')];const sectionObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)navLinks.forEach(link=>link.classList.toggle('active',link.getAttribute('href')===`#${entry.target.id}`))}),{rootMargin:'-35% 0px -55% 0px'});sections.forEach(section=>sectionObserver.observe(section));
if(matchMedia('(pointer:fine)').matches&&!matchMedia('(prefers-reduced-motion:reduce)').matches){document.querySelectorAll('.frame-card').forEach(card=>{card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5;const y=(e.clientY-r.top)/r.height-.5;card.style.transform=`translateY(-8px) perspective(900px) rotateX(${y*-2}deg) rotateY(${x*2}deg)`});card.addEventListener('pointerleave',()=>card.style.transform='')})}

// The PDF in the repository is the single source of truth for the resume.
document.querySelectorAll('a[href="resume.html"]').forEach(link=>{link.href='Jaya_Sharma_Resume.pdf';link.setAttribute('target','_blank');link.setAttribute('rel','noopener')});
const resumeDownload=document.querySelector('.resume-actions a[download]');if(resumeDownload){resumeDownload.href='Jaya_Sharma_Resume.pdf';resumeDownload.setAttribute('target','_blank');resumeDownload.setAttribute('rel','noopener');resumeDownload.removeAttribute('download');resumeDownload.textContent='View / Save Resume ↗'}
